version: 2.1
orbs:
  python: circleci/python@2.1.1
commands:
  install_cloud_sql:
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}

jobs:
  prelims:
    docker:
      - image:
          - image: google/cloud_sdk
            auth:
              username: $ETL_FLOW_CLOUD_SDK_USER
              password: $ETL_FLOW_CLOUD_SDK_PASSWORD

    working_directory: ~/etl_flow
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            python -m temp.helloworld
            ls -al
#      - import_db
#      - create_bq_datasets
#      - detect_tcia_collection_name_changes
#      - revise_original_collections_metadata_idc_source_table
#      - revise_analysis_results_metadata_idc_source_table
#      - update_analysis_results_descriptions_table

#  preingestion:
#    docker:
#      - image:
#          - image: cimg/python:3.8.14
#    steps:
#      -update_idc_xxx_table_hierarchy
workflows:
  flow:
    jobs:
      - prelims

