version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.1

jobs:
    use-gcp:
      working_directory: ~/etl_flow
      executor: gcp-cli/google
      steps:
        - run:
            name: Set HOME
            command: |
              echo "export HOME=/home/circleci/${CIRCLE_PROJECT_REPONAME}" >> "$BASH_ENV"
        - checkout
        - run:
            name: Install sudo and ps
            command: |
              apt-get -y update && apt-get -y install sudo procps
        - gcp-cli/setup:
            service_account_email: IDC_ETL_PROCESSING_SA
            gcloud_service_key: IDC_ETL_PROCESSING_SERVICE_KEY
            google_project_id: ETL_FLOW_PROJECT_ID
            google_project_number: ETL_FLOW_PROJECT_NUMBER
        - run:
            name: Set PYTHONPATH
            command: |
              echo "export PYTHONPATH=${PWD}:/home/circleci/${CIRCLE_PROJECT_REPONAME}:/home/circleci/${CIRCLE_PROJECT_REPONAME}/lib" >> "$BASH_ENV"
        - run:
            name: list some stuff
            command: |
              echo $PWD
              echo $HOME
              echo ${PYTHONPATH}
        - restore_cache:
            keys:
              - etl-flow-lib-{{ checksum "requirements.txt" }}
        - run:
            name: Staging
            command: |

              sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
              sudo -E /bin/bash ./shell/install-deps.sh

              if [ ! -d "lib" ]; then
                echo No dir lib
              else
                echo Directory lib exists
                echo ls lib:
                ls lib
              fi
              if [ ! -d "${HOME}/lib" ]; then
                echo No dir ${HOME}/lib
              else
                echo Directory ${HOME}/lib exists
                echo ls ${HOME}/lib:
                ls ${HOME}/lib
              fi
        - save_cache:
            key: etl-flow-lib-{{ checksum "requirements.txt" }}
            paths:
              - /${HOME}/lib
        - run:
            name: Install Cloud SQL Proxy
            command: |
              mkdir -p $HOME/google-cloud-sdk/
              curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.9.0/cloud-sql-proxy.linux.amd64
              chmod +x cloud-sql-proxy
              mv cloud-sql-proxy $HOME/google-cloud-sdk/
        - run:
            name: Run Cloud SQL Proxy
            command: |
              echo $IDC_ETL_PROCESSING_SERVICE_KEY >> $HOME/credentials_file
              $HOME/google-cloud-sdk/cloud-sql-proxy --credentials-file $HOME/credentials_file --address 0.0.0.0 --port 5433 $CLOUD_SQL_INSTANCE_NAME
            background: true
        - run:
            name: list some stuff
            command: |
              echo $PWD
              echo $HOME
              echo ${PYTHONPATH}
              ps -ef
        - run:
            name: Run tests
            command: |
              # Run your tests that connect to the Cloud SQL instance
              python3 ./preingestion/detect_tcia_collection_name_changes.py

workflows:
  run-cloud-sql-proxy:
    jobs:
      - use-gcp:
          context: gcp-context


