version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.1

jobs:
#  run-cloud-sql-proxy:
#    docker:
#      - image: cimg/python:3.9
#    resource_class: medium
#    steps:
#      - checkout
#      - gcp-cli/initialize:
#          project-id: $GCP_PROJECT_ID
#          service-account-key: $GCP_SA_KEY

    use-gcp:
      working_directory: ~/etl_flow
      executor: gcp-cli/google
      steps:
        - checkout
        - gcp-cli/setup:
            service_account_email: IDC_ETL_PROCESSING_SA
            gcloud_service_key: IDC_ETL_PROCESSING_SERVICE_KEY
            google_project_id: ETL_FLOW_PROJECT_ID
            google_project_number: ETL_FLOW_PROJECT_NUMBER
        - run:
            name: Install Cloud SQL Proxy
            command: |
              mkdir -p $HOME/google-cloud-sdk/
              export CLOUD_SQL_PROXY_VERSION=v1.19.1
              curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
              chmod +x cloud_sql_proxy
              mv cloud_sql_proxy $HOME/google-cloud-sdk/
        - run:
            name: Install sudo
            command: |
              apt-get install sudo
        - run:
            name: Staging
            command: |
              sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
        - run:
            name: Run Cloud SQL Proxy
            command: |
              $HOME/google-cloud-sdk/cloud_sql_proxy -instances=$CLOUD_SQL_INSTANCE_NAME=tcp:5433
            background: true
        - run:
            name: Run tests
            command: |
              # Run your tests that connect to the Cloud SQL instance
              ./preingestion/detect_tcia_collection_name_changes.py

workflows:
  run-cloud-sql-proxy:
    jobs:
      - use-gcp:
          context: gcp-context


