version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.1

jobs:
  run-cloud-sql-proxy:
    docker:
      - image: cimg/python:3.9
    resource_class: medium
    steps:
      - checkout
      - gcp-cli/initialize:
          project-id: $GCP_PROJECT_ID
          service-account-key: $GCP_SA_KEY
      - run:
          name: Install Cloud SQL Proxy
          command: |
            mkdir -p $HOME/google-cloud-sdk/
            export CLOUD_SQL_PROXY_VERSION=v1.19.1
            wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
            chmod +x cloud_sql_proxy
            mv cloud_sql_proxy $HOME/google-cloud-sdk/
      - run:
          name: Run Cloud SQL Proxy
          command: |
            $HOME/google-cloud-sdk/cloud_sql_proxy -instances=$CLOUD_SQL_INSTANCE_NAME=tcp:5432
          background: true
      - run:
          name: Run tests
          command: |
            # Run your tests that connect to the Cloud SQL instance
            preingestion/detect_tcia_collection_name_changes.py

workflows:
  run-cloud-sql-proxy:
    jobs:
      - run-cloud-sql-proxy:
          context: gcp-context


