SELECT
  SeriesInstanceUID,
  SOPInstanceUID,
  SAFE_CAST(SliceThickness AS FLOAT64) AS SliceThickness,
  CASE
    WHEN UPPER(BodyPartExamined) IN ('PORT ABDOMEN', 'J BRZUSZNA', 'ABD', 'BD BD MR ABDOME', 'BD CT ABD WO_W', 'BD CT ABD WO_W C') THEN 'ABDOMEN'
    WHEN UPPER(BodyPartExamined) IN ('PELVIS', 'BONYPELVIS') THEN 'PELVIS'
    WHEN UPPER(BodyPartExamined) IN ('PET_ABDOMEN_PEL', 'CT ABD PELVIS', 'ABD PEL', 'ABD PELV', 'ABDOMEN PEL', 'ABDOMEN PELVIS', 'ABDOMEN TO PEL', 'ABDOMEN_PELVIS', 'ABDPEL', 'ABDOMEN_PELVIS C', 'PET_ABDOMEN_PELV') THEN 'ABDOMENPELVIS'
    WHEN UPPER(BodyPartExamined) IN (
    'TH CT CHEST WO',
    'SPI CHEST 5MM',
    'PORT CHEST',
    'PET_CT SCAN CHE',
    'CTA CHEST',
    'CT CHEST W_ENHA',
    'CT CHEST WITH C',
    'CT CHEST WO CE',
    'AP PORTABLE CHE',
    'CHEST COMPUTED',
    'CHEST INF',
    'CHEST NO GRID',
    'CHEST PE',
    'CHEST',
    'CT CHEST W_ENHAN',
    'CHEST COMPUTED T',
    'PET_CT SCAN CHES',
    'AP PORTABLE CHES',
    'CHEST (THORAX) W',
    'TH CT CHEST WO C') THEN 'CHEST'
    WHEN UPPER(BodyPartExamined) IN ('MR BRAIN W CON', 'MR NEURO BRAIN', 'BRAIN W/WO_AH', 'BRAIN W/WO_AH32') THEN 'BRAIN'
    WHEN UPPER(BodyPartExamined) IN (
    'CHEST_TO_PELVIS',
    'CAP',
    'CAP INFUSION',
    'CHABDPELV',
    'CHEST ABD PEL',
    'CHEST ABD PELVI',
    'CHEST TO PEL',
    'CHEST TO PELVIS',
    'CHEST_ABD_PEL',
    'CHEST ABD PELVIS') THEN 'CHESTABDPELVIS'
    WHEN UPPER(BodyPartExamined) IN ('CERVICAL_SPINE') THEN 'CSPINE'
    WHEN UPPER(BodyPartExamined) IN ('THORAXABD', 'CT_CHABD', 'CHEST ABDOMEN', 'CHEST_ABDOMEN', 'CHEST/ABD') THEN 'CHESTABDOMEN'
    WHEN UPPER(BodyPartExamined) IN ('CT 3PHASE REN', 'KIDNEY') THEN 'KIDNEY'
    WHEN UPPER(BodyPartExamined) IN ('THORAX CT _AH05', 'THORAX CT _OT01', 'CT THORAX W CNT', 'THORAX') THEN 'THORAX'
    WHEN UPPER(BodyPartExamined) IN ('HEAD_NECK', 'HEAD-AND-NECK', 'HEAD-NECK', 'HEADANDNECK') THEN 'HEADNECK'
    WHEN UPPER(BodyPartExamined) IN ('LUMBO-SACRAL SP', 'LUMBO-SACRAL SPI') THEN 'LSSPINE'
    WHEN UPPER(BodyPartExamined) IN ('NECK TO PELVIS', 'NECKCHESTABDPEL') THEN 'NECKCHESTABDPELV'
    WHEN UPPER(BodyPartExamined) IN ('THORACIC SPINE') THEN 'TSPINE'
    WHEN UPPER(BodyPartExamined) IN ('WHOLE BODY') THEN 'WHOLEBODY'
    WHEN UPPER(BodyPartExamined) IN ('LEFT BREAST', 'RIGHT BREAST') THEN 'BREAST'
    WHEN UPPER(BodyPartExamined) IN ('LEG') THEN 'LOWERLIMB'
  ELSE
  BodyPartExamined
END
  AS BodyPartExamined,
  IF(ARRAY_LENGTH(SPLIT(ocm.cancer_types, ',')) <=5, ocm.cancer_types, 'Various') AS cancer_types
FROM
  `{project}.{dataset}.dicom_all` AS da
JOIN
  `{project}.{dataset}.original_collections_metadata` AS ocm
ON
  da.collection_id = ocm.collection_id
