#
# Copyright 2015-2021, Institute for Systems Biology
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Create Analytics Hub listings for new datasets

import settings
import argparse
from utilities.analytic_hub_utils import create_listing
from utilities.bq_helpers import create_BQ_dataset
from google.api_core.exceptions import NotFound
from google.cloud import bigquery

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--idc_icon', default="./idc_icon.png")
    args = parser.parse_args()

    client = bigquery.Client(project='nci-idc-bigquery-data')

    args.description = \
'''Metadata index for the data in National Cancer Institute Imaging Data Commons | Radiology and digital pathology images, annotations in DICOM format + clinical data'''

    args.documentation = \
'''NCI Imaging Data Commons (IDC) (https://portal.imaging.datacommons.cancer.gov/) is a cloud-based environment containing publicly available cancer imaging data co-located with analysis and exploration tools and resources. IDC is a node within the broader NCI Cancer Research Data Commons (CRDC) (https://datacommons.cancer.gov/) infrastructure that provides secure access to a large, comprehensive, and expanding collection of cancer research data.

IDC curates and shares imaging data in DICOM format, available for download from public Google Cloud Storage buckets. As of v17, IDC contains over 45 TB of imaging data in DICOM format, including radiology and pathology images, image annotations, and various image-derived items (including those generated by AI tools) such as volumetric segmentations, radiomics features and parametric maps.

This dataset provides the searchable index of the metadata accompanying the shared DICOM files. To get started with using this dataset, please see IDC Getting Started tutorials here: https://github.com/ImagingDataCommons/IDC-Tutorials/tree/master/notebooks/getting_started.

Terms of Use: If you use this dataset, please acknowledge IDC as described in this article: https://learn.canceridc.dev/frequently-asked-questions#how-to-acknowledge-idc. If you use the DICOM files referenced from this dataset tables, please use the information about license and attribution assigned on a per-file basis, as described in the Getting Started tutorials: https://github.com/ImagingDataCommons/IDC-Tutorials/tree/master/notebooks/getting_started.'''

    # Create idc_vX listing
    args.listing_id = f"idc_v{settings.CURRENT_VERSION}"
    args.display_name = f"NCI Imaging Data Commons Imaging Metadata Catalog v{settings.CURRENT_VERSION}"
    args.dataset = f"projects/{settings.AH_PROJECT}/datasets/idc_v{settings.CURRENT_VERSION}"
    try:
        dst_dataset = client.get_dataset(args.dataset)
    except NotFound:
        breakpoint()
        description = f"Imaging Data Commons (IDC) - The Cancer Imaging Archive (TCIA) v{settings.CURRENT_VERSION} data"
        dst_dataset = create_BQ_dataset(client, args.dataset, description)
    listing = create_listing(args)

    # Create idc_vX_clinical listing
    args.listing_id = f"idc_v{settings.CURRENT_VERSION}_clinical"
    args.display_name = f"NCI Imaging Data Commons Clinical Metadata Catalog v{settings.CURRENT_VERSION}"
    args.dataset = f"projects/{settings.AH_PROJECT}/datasets/idc_v{settings.CURRENT_VERSION}_clinical"
    try:
        dst_dataset = client.get_dataset(args.dataset)
    except NotFound:
        breakpoint()
        description = f"Imaging Data Commons (IDC) - The Cancer Imaging Archive (TCIA) v{settings.CURRENT_VERSION} clinical data"
        dst_dataset = create_BQ_dataset(client, args.dataset, description)
    listing = create_listing(args)
